# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'Picker' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!
  pod 'IQKeyboardManagerSwift', '~> 4.0.8'


  # Pods for Picker

  target 'PickerTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'PickerUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
